<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // CATATAN: harga_beli dan stok_tersedia TIDAK diisi di sini.
        // harga_beli akan diupdate otomatis saat seeder pembelian dijalankan.
        // stok_tersedia akan bertambah otomatis dari seeder pembelian.

        $products = [

            // =============================================
            // KATEGORI 1 - ALAT TULIS
            // =============================================

            // Subkategori: Pulpen (sub_category_id: 1)
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 1, 'kode_produk' => 'ATK-PEN-001', 'nama_produk' => 'Pulpen Pilot G2 0.5mm Hitam',            'deskripsi' => 'Pulpen gel Pilot G2 tinta hitam ujung 0.5mm, nyaman dipakai menulis lama',                          'harga_jual' => 12000,  'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 1, 'kode_produk' => 'ATK-PEN-002', 'nama_produk' => 'Pulpen Pilot G2 0.7mm Biru',             'deskripsi' => 'Pulpen gel Pilot G2 tinta biru ujung 0.7mm, aliran tinta lancar',                                   'harga_jual' => 12000,  'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 2, 'kode_produk' => 'ATK-PEN-003', 'nama_produk' => 'Pulpen Ballpoint Joyko BP-101 Box isi 50','deskripsi' => 'Ballpoint Joyko tinta biru 1 box isi 50 pcs, cocok untuk kebutuhan kantor',                        'harga_jual' => 65000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 1, 'kode_produk' => 'ATK-PEN-004', 'nama_produk' => 'Pulpen Snowman Sign Pen Hitam',           'deskripsi' => 'Pulpen fiber tip Snowman untuk tanda tangan dan dokumen resmi',                                  'harga_jual' => 8000,   'stok_minimum' => 30,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 1, 'kode_produk' => 'ATK-PEN-005', 'nama_produk' => 'Pulpen Uni-ball Eye 0.5mm Hitam',         'deskripsi' => 'Pulpen rollerball Uni-ball Eye tinta hitam waterproof, ujung 0.5mm',                             'harga_jual' => 18000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 1, 'kode_produk' => 'ATK-PEN-006', 'nama_produk' => 'Pulpen Zebra Sarasa Clip 0.5mm Hitam',    'deskripsi' => 'Pulpen gel Zebra Sarasa Clip tinta hitam, ujung 0.5mm, clip stainless',                        'harga_jual' => 15000,  'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 1, 'unit_id' => 2, 'kode_produk' => 'ATK-PEN-007', 'nama_produk' => 'Pulpen Standard AE-7 Box isi 50',         'deskripsi' => 'Ballpoint Standard AE-7 tinta hitam 1 box isi 50 pcs, ekonomis untuk kantor',                  'harga_jual' => 55000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Pensil (sub_category_id: 2)
            ['category_id' => 1, 'sub_category_id' => 2, 'unit_id' => 1, 'kode_produk' => 'ATK-PCL-001', 'nama_produk' => 'Pensil Faber Castell 2B',                  'deskripsi' => 'Pensil kayu Faber Castell 2B, cocok untuk gambar teknik dan menulis',                          'harga_jual' => 5000,   'stok_minimum' => 50,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 2, 'unit_id' => 1, 'kode_produk' => 'ATK-PCL-002', 'nama_produk' => 'Pensil Faber Castell HB',                   'deskripsi' => 'Pensil kayu Faber Castell HB standar ujian nasional',                                          'harga_jual' => 4500,   'stok_minimum' => 50,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 2, 'unit_id' => 1, 'kode_produk' => 'ATK-PCL-003', 'nama_produk' => 'Mechanical Pencil Pentel Graph 1000 0.5mm','deskripsi' => 'Pensil mekanik Pentel Graph 1000 ujung 0.5mm grip karet anti selip',                          'harga_jual' => 80000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 2, 'unit_id' => 1, 'kode_produk' => 'ATK-PCL-004', 'nama_produk' => 'Mechanical Pencil Staedtler 925 0.5mm',    'deskripsi' => 'Pensil mekanik Staedtler 925 25 ujung 0.5mm, badan metal ringan',                             'harga_jual' => 95000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 2, 'unit_id' => 3, 'kode_produk' => 'ATK-PCL-005', 'nama_produk' => 'Isi Pensil Mekanik 0.5mm 2B Pentel Pack',  'deskripsi' => 'Refill lead pensil mekanik 0.5mm 2B Pentel, 1 pack isi 12 batang',                            'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Spidol (sub_category_id: 3)
            ['category_id' => 1, 'sub_category_id' => 3, 'unit_id' => 1, 'kode_produk' => 'ATK-SPD-001', 'nama_produk' => 'Spidol Whiteboard Snowman WB-30 Hitam',    'deskripsi' => 'Spidol whiteboard Snowman tinta hitam mudah dihapus tahan lama',                             'harga_jual' => 11000,  'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 3, 'unit_id' => 1, 'kode_produk' => 'ATK-SPD-002', 'nama_produk' => 'Spidol Whiteboard Snowman WB-30 Merah',    'deskripsi' => 'Spidol whiteboard Snowman tinta merah, ujung chisel tip 2-5mm',                             'harga_jual' => 11000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 3, 'unit_id' => 9, 'kode_produk' => 'ATK-SPD-003', 'nama_produk' => 'Spidol Permanent Marker Artline Set 4 Warna','deskripsi' => 'Set 4 spidol permanent Artline hitam merah biru hijau, tinta anti air',                    'harga_jual' => 42000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 3, 'unit_id' => 1, 'kode_produk' => 'ATK-SPD-004', 'nama_produk' => 'Spidol Koi Brush Pen Hitam',               'deskripsi' => 'Brush pen Koi tinta hitam berbasis air untuk lettering dan kaligrafi',                       'harga_jual' => 22000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 3, 'unit_id' => 1, 'kode_produk' => 'ATK-SPD-005', 'nama_produk' => 'Spidol Marking Pen Joyko MP-01 Hitam',     'deskripsi' => 'Marking pen Joyko tinta hitam permanent, cocok untuk kardus dan kayu',                       'harga_jual' => 8500,   'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Stabilo / Highlighter (sub_category_id: 4)
            ['category_id' => 1, 'sub_category_id' => 4, 'unit_id' => 1, 'kode_produk' => 'ATK-STB-001', 'nama_produk' => 'Stabilo Boss Original Kuning',             'deskripsi' => 'Highlighter Stabilo Boss warna kuning tinta fluorescent ujung rata',                         'harga_jual' => 14000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 4, 'unit_id' => 1, 'kode_produk' => 'ATK-STB-002', 'nama_produk' => 'Stabilo Boss Original Hijau',              'deskripsi' => 'Highlighter Stabilo Boss warna hijau tinta fluorescent ujung rata',                         'harga_jual' => 14000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 4, 'unit_id' => 1, 'kode_produk' => 'ATK-STB-003', 'nama_produk' => 'Stabilo Boss Original Pink',               'deskripsi' => 'Highlighter Stabilo Boss warna pink tinta fluorescent ujung rata',                          'harga_jual' => 14000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 4, 'unit_id' => 9, 'kode_produk' => 'ATK-STB-004', 'nama_produk' => 'Joyko Highlighter Set 6 Warna',            'deskripsi' => 'Set 6 stabilo Joyko berbagai warna cocok untuk belajar dan arsip dokumen',                 'harga_jual' => 28000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 4, 'unit_id' => 1, 'kode_produk' => 'ATK-STB-005', 'nama_produk' => 'Zebra Mildliner Double-ended Biru',         'deskripsi' => 'Highlighter Zebra Mildliner double-ended warna biru muda, tinta mild color',                 'harga_jual' => 28000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Pensil Warna / Rautan (sub_category_id: 5)
            ['category_id' => 1, 'sub_category_id' => 5, 'unit_id' => 1, 'kode_produk' => 'ATK-RAU-001', 'nama_produk' => 'Rautan Pensil Faber Castell Kotak Plastik', 'deskripsi' => 'Rautan pensil Faber Castell dengan tempat serutan, bahan plastik ABS',                      'harga_jual' => 8000,   'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 5, 'unit_id' => 1, 'kode_produk' => 'ATK-RAU-002', 'nama_produk' => 'Rautan Pensil Elektrik Joyko ES-200',        'deskripsi' => 'Rautan pensil elektrik Joyko ES-200, otomatis berhenti saat pensil sudah lancip',           'harga_jual' => 70000,  'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 1, 'sub_category_id' => 5, 'unit_id' => 1, 'kode_produk' => 'ATK-RAU-003', 'nama_produk' => 'Penggaris Besi 30cm Joyko',                  'deskripsi' => 'Penggaris besi stainless steel 30cm Joyko, skala mm dan cm jelas',                         'harga_jual' => 18000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 2 - KERTAS & BUKU
            // =============================================

            // Subkategori: Kertas HVS (sub_category_id: 6 -> mapped to 11 in SubCategory, tapi ikuti ProductSeeder lama)
            ['category_id' => 2, 'sub_category_id' => 6,  'unit_id' => 5, 'kode_produk' => 'KRT-HVS-001', 'nama_produk' => 'Kertas HVS A4 70gr Sinar Dunia 1 Rim',      'deskripsi' => 'Kertas HVS A4 70 gram Sinar Dunia 500 lembar per rim',                                     'harga_jual' => 55000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 6,  'unit_id' => 5, 'kode_produk' => 'KRT-HVS-002', 'nama_produk' => 'Kertas HVS F4 80gr IK Plus 1 Rim',          'deskripsi' => 'Kertas HVS F4 80 gram IK Plus 500 lembar per rim, putih cerah',                           'harga_jual' => 68000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 6,  'unit_id' => 5, 'kode_produk' => 'KRT-HVS-003', 'nama_produk' => 'Kertas HVS A4 80gr Paperline 1 Rim',         'deskripsi' => 'Kertas HVS A4 80 gram Paperline Gold 500 lembar, untuk cetak berkualitas',               'harga_jual' => 72000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 6,  'unit_id' => 6, 'kode_produk' => 'KRT-HVS-004', 'nama_produk' => 'Kertas HVS Warna A4 70gr Merah Per Lembar',  'deskripsi' => 'Kertas HVS warna merah A4 70gr, dijual per lembar untuk kebutuhan dekorasi',              'harga_jual' => 400,    'stok_minimum' => 100, 'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 6,  'unit_id' => 6, 'kode_produk' => 'KRT-HVS-005', 'nama_produk' => 'Kertas HVS Warna A4 70gr Biru Per Lembar',   'deskripsi' => 'Kertas HVS warna biru A4 70gr, dijual per lembar untuk kebutuhan dekorasi',               'harga_jual' => 400,    'stok_minimum' => 100, 'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Buku Tulis (sub_category_id: 7 -> mapped to 17)
            ['category_id' => 2, 'sub_category_id' => 7,  'unit_id' => 1,  'kode_produk' => 'KRT-BKT-001', 'nama_produk' => 'Buku Tulis Sinar Dunia 58 Lembar',           'deskripsi' => 'Buku tulis bergaris Sinar Dunia 58 lembar cover motif',                                   'harga_jual' => 6500,   'stok_minimum' => 30,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 7,  'unit_id' => 10, 'kode_produk' => 'KRT-BKT-002', 'nama_produk' => 'Buku Tulis Kiky 38 Lembar 1 Kodi',           'deskripsi' => 'Buku tulis Kiky 38 lembar 1 kodi isi 20 buku harga grosir',                              'harga_jual' => 78000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 7,  'unit_id' => 1,  'kode_produk' => 'KRT-BKT-003', 'nama_produk' => 'Buku Tulis Motif A5 100 Lembar Hardcover',    'deskripsi' => 'Buku tulis A5 100 lembar hardcover motif aesthetic untuk jurnal harian',                  'harga_jual' => 28000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 7,  'unit_id' => 1,  'kode_produk' => 'KRT-BKT-004', 'nama_produk' => 'Buku Tulis Kotak 1cm A4 50 Lembar',           'deskripsi' => 'Buku tulis kotak 1cm ukuran A4 50 lembar untuk teknik dan matematika',                   'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Buku Gambar / Agenda (sub_category_id: 8 -> mapped to 18)
            ['category_id' => 2, 'sub_category_id' => 8,  'unit_id' => 1,  'kode_produk' => 'KRT-AGD-001', 'nama_produk' => 'Agenda Harian Kalender 2025 A5 Hardcover',   'deskripsi' => 'Agenda harian 2025 ukuran A5 hardcover, 1 halaman per hari dengan kolom catatan',         'harga_jual' => 55000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 8,  'unit_id' => 1,  'kode_produk' => 'KRT-AGD-002', 'nama_produk' => 'Weekly Planner A5 Spiral 52 Minggu',          'deskripsi' => 'Weekly planner spiral A5 isi 52 halaman mingguan plus catatan bulanan',                  'harga_jual' => 45000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 8,  'unit_id' => 1,  'kode_produk' => 'KRT-AGD-003', 'nama_produk' => 'Buku Catatan Meeting A4 100 Halaman',         'deskripsi' => 'Buku catatan meeting A4 100 halaman bergaris dengan kolom agenda dan action item',        'harga_jual' => 35000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Sticky Notes / Kertas Karton (sub_category_id: 9 -> mapped to 19)
            ['category_id' => 2, 'sub_category_id' => 9,  'unit_id' => 6,  'kode_produk' => 'KRT-KRN-001', 'nama_produk' => 'Kertas Karton Duplex 270gr A3 Per Lembar',   'deskripsi' => 'Kertas karton duplex 270gr ukuran A3 untuk cover dan kemasan',                            'harga_jual' => 2500,   'stok_minimum' => 50,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 9,  'unit_id' => 6,  'kode_produk' => 'KRT-KRN-002', 'nama_produk' => 'Kertas Buffalo A4 Merah Per Lembar',          'deskripsi' => 'Kertas buffalo tebal warna merah A4 untuk cover jilid dan kerajinan tangan',             'harga_jual' => 1500,   'stok_minimum' => 60,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 9,  'unit_id' => 6,  'kode_produk' => 'KRT-KRN-003', 'nama_produk' => 'Kertas Ivory 210gr A4 Per Lembar',            'deskripsi' => 'Kertas ivory 210gr A4 untuk cetak undangan dan kartu premium',                           'harga_jual' => 2000,   'stok_minimum' => 60,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Amplop / Sticky Notes (sub_category_id: 10 -> mapped to 20)
            ['category_id' => 2, 'sub_category_id' => 10, 'unit_id' => 3,  'kode_produk' => 'KRT-STN-001', 'nama_produk' => 'Post-it 3M 3x3 Inch Warna Pastel 1 Pack',    'deskripsi' => 'Sticky note 3M Post-it 3x3 inch warna pastel 1 pack isi 5 warna',                       'harga_jual' => 45000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 10, 'unit_id' => 1,  'kode_produk' => 'KRT-STN-002', 'nama_produk' => 'Sticky Note Joyko SN-04 75x75mm Kuning',      'deskripsi' => 'Sticky note Joyko 75x75mm warna kuning isi 100 lembar per pad',                         'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 2, 'sub_category_id' => 10, 'unit_id' => 9,  'kode_produk' => 'KRT-STN-003', 'nama_produk' => 'Index Tab Sticky Notes 5 Warna Set',          'deskripsi' => 'Index tab sticky notes 5 warna 1 set untuk penanda halaman buku dan dokumen',            'harga_jual' => 18000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 3 - PENGHAPUS & KOREKTOR
            // =============================================

            // Subkategori: Penghapus Pensil (sub_category_id: 11 -> mapped to 21)
            ['category_id' => 3, 'sub_category_id' => 11, 'unit_id' => 1, 'kode_produk' => 'PHP-ERS-001', 'nama_produk' => 'Penghapus Faber Castell Dust Free',            'deskripsi' => 'Penghapus pensil Faber Castell Dust Free, bersih tidak meninggalkan bekas',             'harga_jual' => 6500,   'stok_minimum' => 25,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 11, 'unit_id' => 1, 'kode_produk' => 'PHP-ERS-002', 'nama_produk' => 'Penghapus Staedtler Mars Plastic',              'deskripsi' => 'Penghapus premium Staedtler Mars Plastic, bersih sempurna untuk pensil dan rapido',       'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 11, 'unit_id' => 1, 'kode_produk' => 'PHP-ERS-003', 'nama_produk' => 'Penghapus Kneaded Eraser Abu-abu',              'deskripsi' => 'Penghapus kneaded bisa dibentuk, untuk pensil gambar dan arang',                          'harga_jual' => 10000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Tip-Ex Cair (sub_category_id: 12 -> mapped to 23)
            ['category_id' => 3, 'sub_category_id' => 12, 'unit_id' => 1, 'kode_produk' => 'PHP-TPC-001', 'nama_produk' => 'Tip-Ex Cair Snowman Correction Fluid 20ml',   'deskripsi' => 'Cairan korektor Snowman 20ml cepat kering cocok untuk semua jenis kertas',               'harga_jual' => 9500,   'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 12, 'unit_id' => 1, 'kode_produk' => 'PHP-TPC-002', 'nama_produk' => 'Tip-Ex Cair Joyko CF-01 18ml',                  'deskripsi' => 'Cairan korektor Joyko 18ml formula cepat kering, kuas lembut presisi',                  'harga_jual' => 8000,   'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Tip-Ex Roll (sub_category_id: 13 -> mapped to 25)
            ['category_id' => 3, 'sub_category_id' => 13, 'unit_id' => 1, 'kode_produk' => 'PHP-TPR-001', 'nama_produk' => 'Tip-Ex Roller Joyko 5mm x 6m',                 'deskripsi' => 'Korektor pita roller Joyko 5mm x 6m mudah digunakan hasil rapi',                        'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 13, 'unit_id' => 1, 'kode_produk' => 'PHP-TPR-002', 'nama_produk' => 'Tip-Ex Roller Pentel Ain 4.2mm x 10m',         'deskripsi' => 'Correction tape Pentel Ain 4.2mm x 10m, pita lebih panjang ekonomis',                   'harga_jual' => 27000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 13, 'unit_id' => 1, 'kode_produk' => 'PHP-TPR-003', 'nama_produk' => 'Tip-Ex Roller Tombow Mono 4mm x 6m',           'deskripsi' => 'Correction tape Tombow Mono 4mm x 6m hasil bersih langsung bisa ditulis ulang',         'harga_jual' => 33000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Penghapus Papan Tulis (sub_category_id: 14 -> mapped to 29)
            ['category_id' => 3, 'sub_category_id' => 14, 'unit_id' => 1, 'kode_produk' => 'PHP-WBE-001', 'nama_produk' => 'Penghapus Whiteboard Snowman Felt',            'deskripsi' => 'Penghapus papan tulis whiteboard Snowman bahan felt lembut, pegangan ergonomis',         'harga_jual' => 18000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 3, 'sub_category_id' => 14, 'unit_id' => 1, 'kode_produk' => 'PHP-WBE-002', 'nama_produk' => 'Cairan Pembersih Whiteboard 500ml Spray',      'deskripsi' => 'Cairan pembersih whiteboard spray 500ml, efektif hilangkan noda tinta membandel',         'harga_jual' => 38000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 4 - PERLENGKAPAN ARSIP
            // =============================================

            // Subkategori: Ordner (sub_category_id: 15 -> mapped to 33)
            ['category_id' => 4, 'sub_category_id' => 15, 'unit_id' => 1, 'kode_produk' => 'ARS-ORD-001', 'nama_produk' => 'Ordner Bantex A4 Tebal 7cm Merah',             'deskripsi' => 'Ordner Bantex A4 tebal 7cm ring besi kuat warna merah',                                  'harga_jual' => 35000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 15, 'unit_id' => 1, 'kode_produk' => 'ARS-ORD-002', 'nama_produk' => 'Ordner Bantex A4 Tebal 7cm Biru',              'deskripsi' => 'Ordner Bantex A4 tebal 7cm ring besi kuat warna biru',                                   'harga_jual' => 35000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 15, 'unit_id' => 1, 'kode_produk' => 'ARS-ORD-003', 'nama_produk' => 'Ordner Bantex F4 Tebal 5cm Hitam',             'deskripsi' => 'Ordner Bantex F4 tebal 5cm ring besi warna hitam, cocok arsip folio',                    'harga_jual' => 38000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Binder & Paper Clip (sub_category_id: 16 -> mapped to 37/38)
            ['category_id' => 4, 'sub_category_id' => 16, 'unit_id' => 2, 'kode_produk' => 'ARS-CLP-001', 'nama_produk' => 'Binder Clip Joyko No.111 Box isi 12',          'deskripsi' => 'Binder clip besar Joyko No.111 1 box isi 12 pcs baja tahan karat',                      'harga_jual' => 13000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 16, 'unit_id' => 2, 'kode_produk' => 'ARS-CLP-002', 'nama_produk' => 'Binder Clip Joyko No.109 Box isi 12',          'deskripsi' => 'Binder clip sedang Joyko No.109 1 box isi 12 pcs, untuk 20-30 lembar',                   'harga_jual' => 10500,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 16, 'unit_id' => 2, 'kode_produk' => 'ARS-CLP-003', 'nama_produk' => 'Paper Clip Joyko PC-33 Box isi 100',           'deskripsi' => 'Paper clip standar Joyko 33mm 1 box isi 100 pcs, bahan besi anti karat',                 'harga_jual' => 8000,   'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Stapler (sub_category_id: 17 -> mapped to 39/40)
            ['category_id' => 4, 'sub_category_id' => 17, 'unit_id' => 1, 'kode_produk' => 'ARS-STP-001', 'nama_produk' => 'Stapler Kangaro DS-23S Heavy Duty',             'deskripsi' => 'Stapler Kangaro DS-23S kapasitas 30 lembar badan logam kokoh dan presisi',              'harga_jual' => 55000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 17, 'unit_id' => 1, 'kode_produk' => 'ARS-STP-002', 'nama_produk' => 'Stapler Joyko ST-101 Mini',                     'deskripsi' => 'Stapler mini Joyko ST-101 untuk 10 lembar, ringkas dibawa ke mana-mana',                'harga_jual' => 25000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 17, 'unit_id' => 2, 'kode_produk' => 'ARS-STP-003', 'nama_produk' => 'Isi Staples Joyko 24/6 Box isi 20 strip',       'deskripsi' => 'Isi staples Joyko 24/6 standar 1 box isi 20 strip untuk stapler biasa',                  'harga_jual' => 8500,   'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 17, 'unit_id' => 2, 'kode_produk' => 'ARS-STP-004', 'nama_produk' => 'Isi Staples Joyko 23/13 Box isi 20 strip',      'deskripsi' => 'Isi staples Joyko 23/13 untuk stapler heavy duty 1 box 20 strip',                       'harga_jual' => 11000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Clear Holder / Perforator (sub_category_id: 18)
            ['category_id' => 4, 'sub_category_id' => 18, 'unit_id' => 1, 'kode_produk' => 'ARS-PRF-001', 'nama_produk' => 'Perforator 2 Lubang Kangaro DP-480',            'deskripsi' => 'Alat pelubang kertas 2 lubang Kangaro DP-480 kapasitas 30 lembar, badan logam',         'harga_jual' => 48000,  'stok_minimum' => 4,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 18, 'unit_id' => 1, 'kode_produk' => 'ARS-PRF-002', 'nama_produk' => 'Perforator 1 Lubang Joyko HP-01',               'deskripsi' => 'Pelubang kertas 1 lubang Joyko untuk tiket dan kartu, kapasitas 10 lembar',              'harga_jual' => 20000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Box File (sub_category_id: 19)
            ['category_id' => 4, 'sub_category_id' => 19, 'unit_id' => 1, 'kode_produk' => 'ARS-BXF-001', 'nama_produk' => 'Box File Bantex A4 Karton Tebal Hitam',         'deskripsi' => 'Box file Bantex A4 karton tebal warna hitam dengan label slot di punggung',             'harga_jual' => 28000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 4, 'sub_category_id' => 19, 'unit_id' => 1, 'kode_produk' => 'ARS-BXF-002', 'nama_produk' => 'Hanging Folder Plastik Foolscap Merah',         'deskripsi' => 'Hanging folder plastik folio warna merah untuk laci arsip, dengan label tab',            'harga_jual' => 13000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 5 - PERLENGKAPAN MEJA
            // =============================================

            // Subkategori: Penggaris (sub_category_id: 20)
            ['category_id' => 5, 'sub_category_id' => 20, 'unit_id' => 1, 'kode_produk' => 'PMJ-ORG-001', 'nama_produk' => 'Tempat Pensil Akrilik 3 Sekat Bening',         'deskripsi' => 'Tempat pensil meja akrilik bening 3 sekat untuk alat tulis dan aksesoris',              'harga_jual' => 38000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 20, 'unit_id' => 1, 'kode_produk' => 'PMJ-ORG-002', 'nama_produk' => 'Desk Organizer 5 Sekat Hitam Meja',             'deskripsi' => 'Organizer meja 5 sekat warna hitam, tempat dokumen, alat tulis dan aksesoris',         'harga_jual' => 68000,  'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Gunting / Cutter (sub_category_id: 21)
            ['category_id' => 5, 'sub_category_id' => 21, 'unit_id' => 1, 'kode_produk' => 'PMJ-CTR-001', 'nama_produk' => 'Cutter Besar NT Cutter L-500 18mm',             'deskripsi' => 'Cutter besar NT Cutter L-500 mata pisau 18mm badan logam anti slip',                   'harga_jual' => 28000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 21, 'unit_id' => 1, 'kode_produk' => 'PMJ-CTR-002', 'nama_produk' => 'Cutter Kecil Joyko CN-100 9mm',                 'deskripsi' => 'Cutter kecil Joyko CN-100 mata pisau 9mm, ergonomis dan ringan',                        'harga_jual' => 13000,  'stok_minimum' => 12,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 21, 'unit_id' => 1, 'kode_produk' => 'PMJ-CTR-003', 'nama_produk' => 'Gunting Joyko SC-803 18cm',                     'deskripsi' => 'Gunting Joyko SC-803 ukuran 18cm bahan baja tahan karat, grip plastik nyaman',          'harga_jual' => 19000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 21, 'unit_id' => 2, 'kode_produk' => 'PMJ-CTR-004', 'nama_produk' => 'Isi Cutter Besar 18mm Joyko Box isi 10',        'deskripsi' => 'Refill mata pisau cutter 18mm Joyko 1 box isi 10 blade, baja tajam',                    'harga_jual' => 10000,  'stok_minimum' => 12,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Penggaris (sub_category_id: 22)
            ['category_id' => 5, 'sub_category_id' => 22, 'unit_id' => 1, 'kode_produk' => 'PMJ-PNG-001', 'nama_produk' => 'Penggaris Plastik 30cm Joyko',                  'deskripsi' => 'Penggaris plastik transparan 30cm Joyko, skala mm dan cm jelas',                        'harga_jual' => 7000,   'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 22, 'unit_id' => 1, 'kode_produk' => 'PMJ-PNG-002', 'nama_produk' => 'Penggaris Besi 30cm Joyko',                     'deskripsi' => 'Penggaris besi stainless steel 30cm Joyko, skala presisi untuk teknik',                 'harga_jual' => 18000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 22, 'unit_id' => 1, 'kode_produk' => 'PMJ-PNG-003', 'nama_produk' => 'Segitiga Gambar Set Joyko',                     'deskripsi' => 'Set segitiga gambar Joyko 2 pcs sudut 30-60-90 dan 45-45-90 plastik tebal',             'harga_jual' => 24000,  'stok_minimum' => 6,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Lem / Double Tape (sub_category_id: 23)
            ['category_id' => 5, 'sub_category_id' => 23, 'unit_id' => 1, 'kode_produk' => 'PMJ-LEM-001', 'nama_produk' => 'Selotip Bening 3M Scotch 18mm x 30m',           'deskripsi' => 'Selotip transparan 3M Scotch lebar 18mm panjang 30m daya rekat kuat',                  'harga_jual' => 18000,  'stok_minimum' => 15,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 23, 'unit_id' => 1, 'kode_produk' => 'PMJ-LEM-002', 'nama_produk' => 'Glue Stick Faber Castell 20gr',                  'deskripsi' => 'Lem stick Faber Castell 20gr tidak bergelombang cocok untuk kertas dan karton',         'harga_jual' => 12500,  'stok_minimum' => 20,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 23, 'unit_id' => 1, 'kode_produk' => 'PMJ-LEM-003', 'nama_produk' => 'Lem Fox Putih 300gr',                           'deskripsi' => 'Lem putih Fox 300gr serbaguna untuk kertas, kayu, dan kain, daya rekat kuat',           'harga_jual' => 24000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 23, 'unit_id' => 1, 'kode_produk' => 'PMJ-LEM-004', 'nama_produk' => 'Double Tape Busa 3M 1cm x 5m',                  'deskripsi' => 'Double tape busa 3M lebar 1cm panjang 5m, untuk dekorasi dan display',                 'harga_jual' => 22000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Tempat Pensil / Kalkulator (sub_category_id: 24)
            ['category_id' => 5, 'sub_category_id' => 24, 'unit_id' => 1, 'kode_produk' => 'PMJ-KLK-001', 'nama_produk' => 'Kalkulator Casio MX-12B 12 Digit',              'deskripsi' => 'Kalkulator meja Casio MX-12B 12 digit layar besar dual power solar & baterai',          'harga_jual' => 95000,  'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 24, 'unit_id' => 1, 'kode_produk' => 'PMJ-KLK-002', 'nama_produk' => 'Kalkulator Joyko CC-11 8 Digit Saku',           'deskripsi' => 'Kalkulator saku Joyko CC-11 8 digit tipis ringan, solar cell',                          'harga_jual' => 38000,  'stok_minimum' => 4,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 5, 'sub_category_id' => 24, 'unit_id' => 1, 'kode_produk' => 'PMJ-KLK-003', 'nama_produk' => 'Kalkulator Casio FX-350ES Plus Scientific',     'deskripsi' => 'Kalkulator scientific Casio FX-350ES Plus 252 fungsi untuk pelajar dan mahasiswa',       'harga_jual' => 185000, 'stok_minimum' => 2,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 6 - PRINTER & TINTA
            // =============================================

            // Subkategori: Tinta Printer (sub_category_id: 25)
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-001', 'nama_produk' => 'Tinta Epson 664 Black 70ml Original',           'deskripsi' => 'Tinta original Epson 664 hitam 70ml untuk printer L-series',                            'harga_jual' => 80000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-002', 'nama_produk' => 'Tinta Epson 664 Cyan 70ml Original',            'deskripsi' => 'Tinta original Epson 664 warna cyan 70ml untuk printer L-series',                       'harga_jual' => 80000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-003', 'nama_produk' => 'Tinta Epson 664 Magenta 70ml Original',         'deskripsi' => 'Tinta original Epson 664 warna magenta 70ml untuk printer L-series',                    'harga_jual' => 80000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-004', 'nama_produk' => 'Tinta Epson 664 Yellow 70ml Original',          'deskripsi' => 'Tinta original Epson 664 warna kuning 70ml untuk printer L-series',                     'harga_jual' => 80000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 9, 'kode_produk' => 'PRT-TNT-005', 'nama_produk' => 'Tinta Epson 664 Set 4 Warna CMYK Original',     'deskripsi' => 'Set tinta Epson 664 isi 4 warna CMYK untuk printer Epson L-series',                    'harga_jual' => 290000, 'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-006', 'nama_produk' => 'Tinta Compatible Canon PG-745 Black',           'deskripsi' => 'Tinta compatible Canon PG-745 hitam cocok untuk iP2870 dan MG2570',                    'harga_jual' => 40000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-007', 'nama_produk' => 'Tinta Compatible Canon CL-746 Color',           'deskripsi' => 'Tinta compatible Canon CL-746 warna cocok untuk iP2870 dan MG2570',                    'harga_jual' => 48000,  'stok_minimum' => 8,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 25, 'unit_id' => 1, 'kode_produk' => 'PRT-TNT-008', 'nama_produk' => 'Tinta Infus Compatible HP 678 Black',           'deskripsi' => 'Tinta compatible HP 678 hitam untuk printer HP Deskjet 1515 2515 4515',                 'harga_jual' => 35000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Toner Laser (sub_category_id: 26)
            ['category_id' => 6, 'sub_category_id' => 26, 'unit_id' => 1, 'kode_produk' => 'PRT-TNR-001', 'nama_produk' => 'Toner HP 85A CE285A Black Original',             'deskripsi' => 'Toner cartridge original HP 85A untuk LaserJet P1102 dan P1102W',                     'harga_jual' => 520000, 'stok_minimum' => 2,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 26, 'unit_id' => 1, 'kode_produk' => 'PRT-TNR-002', 'nama_produk' => 'Toner Compatible HP 85A CE285A Black',           'deskripsi' => 'Toner compatible HP 85A hitam hasil cetak tajam ekonomis',                             'harga_jual' => 185000, 'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 26, 'unit_id' => 1, 'kode_produk' => 'PRT-TNR-003', 'nama_produk' => 'Toner Compatible Brother TN-2380 Black',         'deskripsi' => 'Toner compatible Brother TN-2380 untuk HL-L2320D MFC-L2720DW',                        'harga_jual' => 200000, 'stok_minimum' => 2,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // Subkategori: Ribbon Printer (sub_category_id: 27)
            ['category_id' => 6, 'sub_category_id' => 27, 'unit_id' => 1, 'kode_produk' => 'PRT-RBN-001', 'nama_produk' => 'Ribbon Epson LX-300 Compatible Black',          'deskripsi' => 'Pita ribbon compatible untuk Epson LX-300 LX-310 hasil cetak tegas',                   'harga_jual' => 40000,  'stok_minimum' => 4,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 6, 'sub_category_id' => 27, 'unit_id' => 1, 'kode_produk' => 'PRT-RBN-002', 'nama_produk' => 'Ribbon Epson FX-890 Compatible Black',          'deskripsi' => 'Pita ribbon compatible untuk Epson FX-890 FX-2190 printer dot matrix',                 'harga_jual' => 48000,  'stok_minimum' => 3,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 7 - PERCETAKAN UMUM
            // (Produk jasa - stok minimum 0, tidak ada stok fisik)
            // =============================================

            ['category_id' => 7, 'sub_category_id' => 28, 'unit_id' => 6, 'kode_produk' => 'CET-BRS-001', 'nama_produk' => 'Cetak Flyer A5 Art Paper 150gr Full Color',     'deskripsi' => 'Cetak flyer A5 full color 2 sisi art paper 150gr, harga per lembar min 100 lembar',    'harga_jual' => 1500,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 28, 'unit_id' => 6, 'kode_produk' => 'CET-BRS-002', 'nama_produk' => 'Cetak Brosur A4 Lipat 3 Art Paper 150gr',       'deskripsi' => 'Cetak brosur A4 lipat 3 full color art paper 150gr harga per lembar min 100',          'harga_jual' => 2800,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 28, 'unit_id' => 6, 'kode_produk' => 'CET-BRS-003', 'nama_produk' => 'Cetak Pamflet A4 HVS 80gr Hitam Putih',         'deskripsi' => 'Cetak pamflet A4 hitam putih HVS 80gr 2 sisi harga per lembar',                        'harga_jual' => 600,    'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 29, 'unit_id' => 2, 'kode_produk' => 'CET-KNM-001', 'nama_produk' => 'Cetak Kartu Nama Art Carton 260gr Box 100',     'deskripsi' => 'Cetak kartu nama full color 2 sisi art carton 260gr finishing glossy 1 box 100 lembar', 'harga_jual' => 45000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 29, 'unit_id' => 2, 'kode_produk' => 'CET-KNM-002', 'nama_produk' => 'Cetak Kartu Nama Linen Emboss Box 100',         'deskripsi' => 'Cetak kartu nama premium bahan linen dengan emboss nama 100 lembar per box',           'harga_jual' => 90000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 30, 'unit_id' => 1, 'kode_produk' => 'CET-KLD-001', 'nama_produk' => 'Cetak Kalender Meja Spiral 14 Lembar A5',      'deskripsi' => 'Cetak kalender meja spiral A5 14 lembar cover tebal full color custom foto',            'harga_jual' => 28000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 30, 'unit_id' => 1, 'kode_produk' => 'CET-KLD-002', 'nama_produk' => 'Cetak Kalender Dinding 13 Lembar A2',           'deskripsi' => 'Cetak kalender dinding 13 lembar A2 full color art paper 150gr custom desain',         'harga_jual' => 45000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 31, 'unit_id' => 2, 'kode_produk' => 'CET-NOT-001', 'nama_produk' => 'Cetak Nota 2 Ply NCR A6 Box 100 set',           'deskripsi' => 'Cetak nota rangkap 2 putih kuning bahan NCR A6 1 box 100 set custom logo',            'harga_jual' => 85000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 31, 'unit_id' => 2, 'kode_produk' => 'CET-NOT-002', 'nama_produk' => 'Cetak Kwitansi 3 Ply NCR A5 Box 50 set',        'deskripsi' => 'Cetak kwitansi rangkap 3 putih kuning merah NCR A5 1 box 50 set custom',               'harga_jual' => 88000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 31, 'unit_id' => 2, 'kode_produk' => 'CET-NOT-003', 'nama_produk' => 'Cetak Faktur Pajak 2 Ply NCR A4 Box 50 set',    'deskripsi' => 'Cetak faktur pajak rangkap 2 NCR A4 format standar pajak 1 box 50 set',                 'harga_jual' => 105000, 'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 32, 'unit_id' => 1, 'kode_produk' => 'CET-BKU-001', 'nama_produk' => 'Cetak Buku A5 Perfect Binding 100 Halaman',    'deskripsi' => 'Cetak buku A5 soft cover perfect binding 100 halaman HVS 80gr isi BW',                 'harga_jual' => 22000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 7, 'sub_category_id' => 32, 'unit_id' => 1, 'kode_produk' => 'CET-BKU-002', 'nama_produk' => 'Cetak Modul A4 Spiral 50 Halaman',              'deskripsi' => 'Cetak modul materi A4 spiral 50 halaman cover art carton 260gr isi HVS BW',            'harga_jual' => 32000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 8 - FINISHING PERCETAKAN
            // (Produk jasa - stok minimum 0)
            // =============================================

            ['category_id' => 8, 'sub_category_id' => 33, 'unit_id' => 6, 'kode_produk' => 'DIG-FOT-001', 'nama_produk' => 'Cetak Foto 4R 10x15cm Glossy',                  'deskripsi' => 'Cetak foto ukuran 4R 10x15cm bahan photo paper glossy warna cerah tajam',             'harga_jual' => 3000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 33, 'unit_id' => 6, 'kode_produk' => 'DIG-FOT-002', 'nama_produk' => 'Cetak Foto A4 Glossy',                          'deskripsi' => 'Cetak foto ukuran A4 bahan photo paper glossy resolusi tinggi',                        'harga_jual' => 15000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 33, 'unit_id' => 6, 'kode_produk' => 'DIG-FOT-003', 'nama_produk' => 'Cetak Foto 2R 6x9cm Doff',                      'deskripsi' => 'Cetak foto 2R 6x9cm bahan photo paper doff anti silau cocok untuk album',               'harga_jual' => 2000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 34, 'unit_id' => 7, 'kode_produk' => 'DIG-BNR-001', 'nama_produk' => 'Cetak Banner Frontlite 340gr Per Meter',         'deskripsi' => 'Cetak banner frontlite 340gr resolusi tinggi harga per meter persegi',                 'harga_jual' => 30000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 34, 'unit_id' => 7, 'kode_produk' => 'DIG-BNR-002', 'nama_produk' => 'Cetak Spanduk Backlite 510gr Per Meter',         'deskripsi' => 'Cetak spanduk backlite 510gr untuk lightbox warna cerah dan tahan lama',               'harga_jual' => 50000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 34, 'unit_id' => 7, 'kode_produk' => 'DIG-BNR-003', 'nama_produk' => 'Cetak Banner Albatros 440gr Per Meter',          'deskripsi' => 'Cetak banner albatros 440gr outdoor tahan cuaca 6 bulan harga per meter persegi',      'harga_jual' => 38000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 35, 'unit_id' => 6, 'kode_produk' => 'DIG-PST-001', 'nama_produk' => 'Cetak Poster A1 Art Paper 150gr',               'deskripsi' => 'Cetak poster A1 full color art paper 150gr resolusi tinggi harga per lembar',           'harga_jual' => 35000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 35, 'unit_id' => 7, 'kode_produk' => 'DIG-PST-002', 'nama_produk' => 'Cetak Canvas Kanvas Foto Per Meter',             'deskripsi' => 'Cetak foto di atas kanvas canvas print resolusi tinggi tanpa bingkai per meter persegi', 'harga_jual' => 90000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 36, 'unit_id' => 1, 'kode_produk' => 'DIG-RUP-001', 'nama_produk' => 'Cetak Roll Up Banner 60x160cm dengan Stand',    'deskripsi' => 'Cetak roll up banner 60x160cm full color beserta stand aluminium portable',             'harga_jual' => 220000, 'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 8, 'sub_category_id' => 36, 'unit_id' => 1, 'kode_produk' => 'DIG-RUP-002', 'nama_produk' => 'Cetak X-Banner 60x160cm dengan Stand',          'deskripsi' => 'Cetak X-banner 60x160cm full color beserta stand X bahan ringan',                      'harga_jual' => 135000, 'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 9 - STIKER & LABEL
            // (Campuran fisik dan jasa)
            // =============================================

            ['category_id' => 9, 'sub_category_id' => 37, 'unit_id' => 6, 'kode_produk' => 'FIN-LAM-001', 'nama_produk' => 'Laminasi Glossy A4 Per Lembar',                 'deskripsi' => 'Layanan laminasi glossy A4 hasil mengkilap tahan air dan goresan',                     'harga_jual' => 4000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 37, 'unit_id' => 6, 'kode_produk' => 'FIN-LAM-002', 'nama_produk' => 'Laminasi Doff A4 Per Lembar',                   'deskripsi' => 'Layanan laminasi doff matte A4 hasil elegan anti silau',                               'harga_jual' => 5000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 37, 'unit_id' => 6, 'kode_produk' => 'FIN-LAM-003', 'nama_produk' => 'Laminasi Glossy F4 Per Lembar',                 'deskripsi' => 'Layanan laminasi glossy F4 folio hasil cerah tahan lama',                              'harga_jual' => 5000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 38, 'unit_id' => 1, 'kode_produk' => 'FIN-JLD-001', 'nama_produk' => 'Jilid Spiral Wire A4 Per Buku',                 'deskripsi' => 'Jilid spiral wire A4 cover transparan belakang karton hitam harga per buku',           'harga_jual' => 15000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 38, 'unit_id' => 1, 'kode_produk' => 'FIN-JLD-002', 'nama_produk' => 'Jilid Lakban Softcover A4 Per Buku',            'deskripsi' => 'Jilid lakban softcover A4 punggung rapi cover plastik bening per buku',                'harga_jual' => 10000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 38, 'unit_id' => 1, 'kode_produk' => 'FIN-JLD-003', 'nama_produk' => 'Jilid Hardcover A4 Per Buku',                   'deskripsi' => 'Jilid hardcover A4 bahan tebal premium untuk skripsi dan laporan formal',               'harga_jual' => 45000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 39, 'unit_id' => 6, 'kode_produk' => 'FIN-POT-001', 'nama_produk' => 'Potong Kertas Per Lembar',                      'deskripsi' => 'Layanan potong kertas presisi per lembar menggunakan mesin guillotine',                 'harga_jual' => 300,    'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 39, 'unit_id' => 1, 'kode_produk' => 'FIN-POT-002', 'nama_produk' => 'Trimming Round Corner Per 100 Lembar',          'deskripsi' => 'Trimming sudut bulat untuk kartu nama dan flyer per 100 lembar',                       'harga_jual' => 10000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 40, 'unit_id' => 6, 'kode_produk' => 'FIN-FLS-001', 'nama_produk' => 'Foil Stamping Gold A5 Per Lembar',              'deskripsi' => 'Finishing foil stamping emas A5 untuk kartu nama dan cover premium per lembar',         'harga_jual' => 12000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 9, 'sub_category_id' => 40, 'unit_id' => 6, 'kode_produk' => 'FIN-FLS-002', 'nama_produk' => 'Emboss Timbul A5 Per Lembar',                   'deskripsi' => 'Finishing emboss timbul A5 tanpa tinta untuk kesan mewah dan elegan per lembar',       'harga_jual' => 15000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],

            // =============================================
            // KATEGORI 10 - AMPLOP & MAP / STIKER LABEL
            // =============================================

            ['category_id' => 10, 'sub_category_id' => 41, 'unit_id' => 6, 'kode_produk' => 'STK-CUT-001', 'nama_produk' => 'Stiker Cutting Vinyl Putih A4 Per Lembar',    'deskripsi' => 'Stiker cutting vinyl warna putih A4 tahan air untuk kendaraan dan outdoor',            'harga_jual' => 15000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 41, 'unit_id' => 6, 'kode_produk' => 'STK-CUT-002', 'nama_produk' => 'Stiker Cutting Transparan A4 Per Lembar',      'deskripsi' => 'Stiker cutting bahan transparan A4 cocok untuk kaca dan produk kemasan',               'harga_jual' => 18000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 42, 'unit_id' => 8, 'kode_produk' => 'STK-LBL-001', 'nama_produk' => 'Label Barcode Thermal 100x50mm Roll isi 500',  'deskripsi' => 'Label barcode thermal paper 100x50mm 1 roll isi 500 lembar untuk printer barcode',     'harga_jual' => 55000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 42, 'unit_id' => 8, 'kode_produk' => 'STK-LBL-002', 'nama_produk' => 'Label Barcode Thermal 58x40mm Roll isi 700',   'deskripsi' => 'Label barcode thermal paper 58x40mm 1 roll isi 700 lembar untuk kasir',               'harga_jual' => 45000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 42, 'unit_id' => 8, 'kode_produk' => 'STK-LBL-003', 'nama_produk' => 'Label Harga Stiker Bulat 16mm Roll isi 1000',  'deskripsi' => 'Stiker label harga bulat 16mm 1 roll 1000 pcs tersedia berbagai warna',                'harga_jual' => 20000,  'stok_minimum' => 10,  'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 42, 'unit_id' => 3, 'kode_produk' => 'STK-LBL-004', 'nama_produk' => 'Label Stiker A4 Polos 65 Label Pack 20 Lembar','deskripsi' => 'Label stiker A4 polos 65 label per lembar 1 pack 20 lembar untuk printer inkjet laser',  'harga_jual' => 40000,  'stok_minimum' => 5,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 43, 'unit_id' => 7, 'kode_produk' => 'STK-VNL-001', 'nama_produk' => 'Cetak Stiker Vinyl Outdoor Full Color Per Meter','deskripsi' => 'Cetak stiker vinyl outdoor full color tahan UV dan air laminasi doff per meter persegi', 'harga_jual' => 60000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 43, 'unit_id' => 7, 'kode_produk' => 'STK-VNL-002', 'nama_produk' => 'Cetak Stiker One Way Vision Per Meter',        'deskripsi' => 'Cetak stiker one way vision untuk kaca tampak satu arah per meter persegi',             'harga_jual' => 85000,  'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 44, 'unit_id' => 6, 'kode_produk' => 'STK-UDG-001', 'nama_produk' => 'Cetak Label Undangan Oval Gold Foil Per Lembar','deskripsi' => 'Cetak label undangan bentuk oval dengan foil gold per lembar min 50 lembar',             'harga_jual' => 6000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
            ['category_id' => 10, 'sub_category_id' => 44, 'unit_id' => 6, 'kode_produk' => 'STK-UDG-002', 'nama_produk' => 'Cetak Stiker Kemasan Produk A4 Full Color',    'deskripsi' => 'Cetak stiker kemasan produk A4 full color art paper glossy per lembar min 20',         'harga_jual' => 9000,   'stok_minimum' => 0,   'gambar_barang' => null, 'status_product' => 'Tersedia'],
        ];

        $products = array_map(fn($item) => array_merge($item, [
            'created_at' => $now,
            'updated_at' => $now,
        ]), $products);

        Product::insert($products);
    }
}