<?php

namespace Database\Seeders;

use App\Models\ServiceOrder;
use App\Models\ServiceCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ServiceOrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * - category_id  → service_categories (ServiceCategoryOrderSeeder)
     * - user_id      → 3 (Pelanggan dari UsersSeeder), sebagian null (walk-in)
     * - created_by   → 2 (Admin)
     * - approved_by  → 1 (Super Admin) untuk yang sudah diproses
     * - Semua status terwakili: pending, approved, rejected, in_progress, completed, cancelled
     */
    public function run(): void
    {
        // Ambil semua kategori, index by nama_jasa untuk kemudahan mapping
        $categories = ServiceCategory::all()->keyBy('nama_jasa');

        // Helper closure: ambil id kategori
        $cat = fn(string $nama) => $categories->get($nama)?->id
            ?? throw new \Exception("Kategori '{$nama}' tidak ditemukan! Jalankan ServiceCategoryOrderSeeder terlebih dahulu.");

        // ============================================================
        // DEFINISI ORDER
        // Setiap order dibuat serealistis mungkin sesuai jenis jasanya
        // ============================================================

        $orders = [

            // ----------------------------------------------------------
            // STATUS: COMPLETED — order lama yang sudah selesai
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250108-0001',
                'user_id'                   => 3,
                'category_id'               => $cat('Desain Kartu Nama'),
                'customer_name'             => 'Budi Hartono',
                'customer_phone'            => '081234567890',
                'customer_email'            => 'budi.hartono@gmail.com',
                'order_title'               => 'Kartu Nama Usaha Bengkel Motor',
                'order_description'         => 'Desain kartu nama untuk bengkel motor Budi Motor. Warna dominan hitam dan merah, tampilan maskulin dan profesional. Sertakan logo bengkel yang sudah ada.',
                'quantity'                  => 1,
                'order_date'                => '2025-01-08',
                'estimated_completion_date' => '2025-01-10',
                'actual_completion_date'    => '2025-01-10',
                'total_price'               => 75000,
                'down_payment'              => 37500,
                'payment'                   => 75000,
                'design_file'               => null,
                'notes'                     => 'Logo bengkel dikirim via WhatsApp',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-01-08 10:30:00',
                'created_by'                => 2,
                'created_at'                => '2025-01-08 09:15:00',
                'updated_at'                => '2025-01-10 16:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250110-0002',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Brosur & Flyer'),
                'customer_name'             => 'Toko Sembako Makmur',
                'customer_phone'            => '082198765432',
                'customer_email'            => null,
                'order_title'               => 'Flyer Promo Sembako Tahun Baru',
                'order_description'         => 'Flyer A5 dua sisi untuk promo harga spesial tahun baru. Produk unggulan: beras, minyak, gula. Warna cerah dan mencolok.',
                'quantity'                  => 1,
                'order_date'                => '2025-01-10',
                'estimated_completion_date' => '2025-01-12',
                'actual_completion_date'    => '2025-01-12',
                'total_price'               => 120000,
                'down_payment'              => 0,
                'payment'                   => 120000,
                'design_file'               => null,
                'notes'                     => '',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-01-10 11:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-01-10 10:00:00',
                'updated_at'                => '2025-01-12 15:30:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250115-0003',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak & Jilid Skripsi / Laporan'),
                'customer_name'             => 'Sari Dewi Anggraini',
                'customer_phone'            => '085711223344',
                'customer_email'            => 'sari.dewi@student.ac.id',
                'order_title'               => 'Cetak & Jilid Skripsi S1 Ekonomi',
                'order_description'         => 'Cetak skripsi 120 halaman, kertas HVS 80gr, jilid hardcover warna hijau tua (warna jurusan ekonomi), emboss nama dan NIM.',
                'quantity'                  => 3,
                'order_date'                => '2025-01-15',
                'estimated_completion_date' => '2025-01-17',
                'actual_completion_date'    => '2025-01-17',
                'total_price'               => 255000,
                'down_payment'              => 100000,
                'payment'                   => 255000,
                'design_file'               => null,
                'notes'                     => 'File skripsi dikirim via Google Drive. 3 eksemplar: 1 perpustakaan, 1 jurusan, 1 pribadi.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-01-15 13:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-01-15 12:00:00',
                'updated_at'                => '2025-01-17 17:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250120-0004',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Spanduk & Banner'),
                'customer_name'             => 'CV Maju Bersama',
                'customer_phone'            => '081370001122',
                'customer_email'            => 'cvmajubersama@gmail.com',
                'order_title'               => 'Spanduk Pembukaan Kantor Baru',
                'order_description'         => 'Spanduk selamat atas pembukaan kantor baru CV Maju Bersama. Ukuran 6x1 meter. Tampilan formal dan elegan, warna navy dan gold.',
                'quantity'                  => 2,
                'order_date'                => '2025-01-20',
                'estimated_completion_date' => '2025-01-22',
                'actual_completion_date'    => '2025-01-22',
                'total_price'               => 200000,
                'down_payment'              => 100000,
                'payment'                   => 200000,
                'design_file'               => null,
                'notes'                     => '2 spanduk dipasang di depan dan samping gedung',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-01-20 09:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-01-20 08:30:00',
                'updated_at'                => '2025-01-22 14:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250128-0005',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Undangan Pernikahan'),
                'customer_name'             => 'Rizal & Fitri',
                'customer_phone'            => '089654321098',
                'customer_email'            => null,
                'order_title'               => 'Undangan Pernikahan Tema Islami Gold',
                'order_description'         => 'Desain undangan pernikahan tema islami modern, warna dominan gold dan putih tulang. Ukuran A5 lipat 2. Sertakan foto pasangan.',
                'quantity'                  => 1,
                'order_date'                => '2025-01-28',
                'estimated_completion_date' => '2025-02-02',
                'actual_completion_date'    => '2025-02-01',
                'total_price'               => 200000,
                'down_payment'              => 100000,
                'payment'                   => 200000,
                'design_file'               => null,
                'notes'                     => 'Foto pasangan dikirim via WhatsApp. Revisi max 3x.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-01-28 10:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-01-28 09:30:00',
                'updated_at'                => '2025-02-01 16:30:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250203-0006',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Logo & Brand Identity'),
                'customer_name'             => 'Warung Kopi Nusantara',
                'customer_phone'            => '082334455667',
                'customer_email'            => 'wkn.medan@gmail.com',
                'order_title'               => 'Logo & Brand Identity Warung Kopi',
                'order_description'         => 'Pembuatan logo baru untuk warung kopi dengan konsep lokal Nusantara. Warna hangat (coklat, krem, hitam). Sertakan panduan penggunaan warna dan font.',
                'quantity'                  => 1,
                'order_date'                => '2025-02-03',
                'estimated_completion_date' => '2025-02-10',
                'actual_completion_date'    => '2025-02-09',
                'total_price'               => 350000,
                'down_payment'              => 175000,
                'payment'                   => 350000,
                'design_file'               => null,
                'notes'                     => 'Referensi desain sudah disepakati via email. Output: AI, PNG, PDF.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-02-03 14:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-02-03 13:00:00',
                'updated_at'                => '2025-02-09 17:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250210-0007',
                'user_id'                   => null,
                'category_id'               => $cat('Laminasi Dokumen Penting'),
                'customer_name'             => 'Hendra Kusuma',
                'customer_phone'            => '081276543210',
                'customer_email'            => null,
                'order_title'               => 'Laminasi Ijazah & Transkip Nilai',
                'order_description'         => 'Laminasi ijazah S1 dan transkrip nilai, masing-masing 1 lembar. Laminasi panas, bahan glossy.',
                'quantity'                  => 2,
                'order_date'                => '2025-02-10',
                'estimated_completion_date' => '2025-02-10',
                'actual_completion_date'    => '2025-02-10',
                'total_price'               => 30000,
                'down_payment'              => 0,
                'payment'                   => 30000,
                'design_file'               => null,
                'notes'                     => 'Selesai di hari yang sama',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-02-10 09:30:00',
                'created_by'                => 2,
                'created_at'                => '2025-02-10 09:00:00',
                'updated_at'                => '2025-02-10 11:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250214-0008',
                'user_id'                   => 3,
                'category_id'               => $cat('Cetak Foto Kanvas'),
                'customer_name'             => 'Pelanggan',
                'customer_phone'            => '081234567891',
                'customer_email'            => 'pelanggan@example.com',
                'order_title'               => 'Cetak Foto Kanvas Valentine',
                'order_description'         => 'Cetak foto couple di atas kanvas ukuran 30x40cm tanpa bingkai. Foto dikirim via WhatsApp resolusi tinggi.',
                'quantity'                  => 1,
                'order_date'                => '2025-02-14',
                'estimated_completion_date' => '2025-02-16',
                'actual_completion_date'    => '2025-02-16',
                'total_price'               => 150000,
                'down_payment'              => 75000,
                'payment'                   => 150000,
                'design_file'               => null,
                'notes'                     => 'Hadiah Valentine, minta dikemas dengan baik',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-02-14 10:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-02-14 09:30:00',
                'updated_at'                => '2025-02-16 15:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250220-0009',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Nota & Kwitansi Custom'),
                'customer_name'             => 'UD Berkah Tani',
                'customer_phone'            => '085370998877',
                'customer_email'            => null,
                'order_title'               => 'Nota Penjualan Hasil Pertanian',
                'order_description'         => 'Desain nota penjualan rangkap 2 untuk UD Berkah Tani. Ukuran A6, logo dan identitas usaha sudah ada. Warna sederhana dan mudah dibaca.',
                'quantity'                  => 1,
                'order_date'                => '2025-02-20',
                'estimated_completion_date' => '2025-02-22',
                'actual_completion_date'    => '2025-02-22',
                'total_price'               => 90000,
                'down_payment'              => 0,
                'payment'                   => 90000,
                'design_file'               => null,
                'notes'                     => 'Setelah desain acc langsung cetak 5 buku nota',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-02-20 11:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-02-20 10:30:00',
                'updated_at'                => '2025-02-22 16:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250305-0010',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Kemasan Produk'),
                'customer_name'             => 'UMKM Keripik Singkong Bu Ani',
                'customer_phone'            => '082211223344',
                'customer_email'            => 'buani.keripik@gmail.com',
                'order_title'               => 'Kemasan Keripik Singkong Varian 3 Rasa',
                'order_description'         => 'Desain kemasan standing pouch untuk keripik singkong, 3 varian rasa: original, balado, dan keju. Ukuran 14x20cm. Tampilan modern dan menggugah selera.',
                'quantity'                  => 3,
                'order_date'                => '2025-03-05',
                'estimated_completion_date' => '2025-03-12',
                'actual_completion_date'    => '2025-03-11',
                'total_price'               => 750000,
                'down_payment'              => 375000,
                'payment'                   => 750000,
                'design_file'               => null,
                'notes'                     => '3 desain berbeda per varian. Output: PDF + mockup presentasi.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-03-05 14:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-03-05 13:30:00',
                'updated_at'                => '2025-03-11 17:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250315-0011',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Plakat & Piagam'),
                'customer_name'             => 'SMA Negeri 5 Medan',
                'customer_phone'            => '061-4512345',
                'customer_email'            => 'sman5medan@disdik.sumut.go.id',
                'order_title'               => 'Plakat Penghargaan Guru Berprestasi',
                'order_description'         => 'Plakat penghargaan untuk 10 guru berprestasi. Bahan akrilik, cetak UV full color, ukuran A4. Desain formal dan elegan dengan logo sekolah.',
                'quantity'                  => 10,
                'order_date'                => '2025-03-15',
                'estimated_completion_date' => '2025-03-22',
                'actual_completion_date'    => '2025-03-21',
                'total_price'               => 1950000,
                'down_payment'              => 975000,
                'payment'                   => 1950000,
                'design_file'               => null,
                'notes'                     => 'Nama-nama guru akan dikirim via email. Pengambilan langsung ke sekolah.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-03-15 10:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-03-15 09:00:00',
                'updated_at'                => '2025-03-21 16:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250325-0012',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Stiker Custom Cutting'),
                'customer_name'             => 'Distro Kaos Medan Underground',
                'customer_phone'            => '082274556677',
                'customer_email'            => 'medanunderground@gmail.com',
                'order_title'               => 'Stiker Cutting Vinyl Logo Band',
                'order_description'         => 'Cetak stiker cutting vinyl untuk 5 band lokal. Masing-masing 20 pcs. Bahan vinyl outdoor, laminasi doff. Ukuran max 10x10cm.',
                'quantity'                  => 100,
                'order_date'                => '2025-03-25',
                'estimated_completion_date' => '2025-03-28',
                'actual_completion_date'    => '2025-03-28',
                'total_price'               => 500000,
                'down_payment'              => 250000,
                'payment'                   => 500000,
                'design_file'               => null,
                'notes'                     => 'File desain masing-masing band dikirim terpisah via email.',
                'status'                    => 'completed',
                'status_pembayaran'         => 'lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-03-25 11:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-03-25 10:30:00',
                'updated_at'                => '2025-03-28 15:00:00',
            ],

            // ----------------------------------------------------------
            // STATUS: IN_PROGRESS — sedang dikerjakan
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250415-0013',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Logo & Brand Identity'),
                'customer_name'             => 'PT Surya Digital Nusantara',
                'customer_phone'            => '081362789001',
                'customer_email'            => 'marketing@suryadigital.id',
                'order_title'               => 'Rebranding Logo & Panduan Brand',
                'order_description'         => 'Redesain logo perusahaan teknologi yang lebih modern dan dinamis. Termasuk panduan brand lengkap: warna primer/sekunder, tipografi, spacing, dan contoh penggunaan di berbagai media.',
                'quantity'                  => 1,
                'order_date'                => '2025-04-15',
                'estimated_completion_date' => '2025-04-30',
                'actual_completion_date'    => null,
                'total_price'               => 350000,
                'down_payment'              => 175000,
                'payment'                   => 175000,
                'design_file'               => null,
                'notes'                     => 'Sedang revisi kedua — menunggu feedback klien untuk pilihan warna.',
                'status'                    => 'in_progress',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-04-15 13:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-04-15 12:00:00',
                'updated_at'                => '2025-04-22 10:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250420-0014',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Kemasan Produk'),
                'customer_name'             => 'Usaha Sambal Bu Rini',
                'customer_phone'            => '085261234567',
                'customer_email'            => null,
                'order_title'               => 'Kemasan Sambal Botol 4 Varian',
                'order_description'         => 'Desain label untuk 4 varian sambal dalam botol kaca 250ml: sambal original, sambal terasi, sambal hijau, sambal matah. Ukuran label 8x12cm, label depan dan belakang.',
                'quantity'                  => 4,
                'order_date'                => '2025-04-20',
                'estimated_completion_date' => '2025-05-05',
                'actual_completion_date'    => null,
                'total_price'               => 1000000,
                'down_payment'              => 500000,
                'payment'                   => 500000,
                'design_file'               => null,
                'notes'                     => 'Sedang dalam proses desain varian pertama. 3 varian lainnya menyusul.',
                'status'                    => 'in_progress',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-04-20 10:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-04-20 09:30:00',
                'updated_at'                => '2025-04-25 14:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250428-0015',
                'user_id'                   => 3,
                'category_id'               => $cat('Jilid Hardcover Skripsi Eksklusif'),
                'customer_name'             => 'Pelanggan',
                'customer_phone'            => '081234567891',
                'customer_email'            => 'pelanggan@example.com',
                'order_title'               => 'Jilid Hardcover Skripsi Eksklusif Teknik Informatika',
                'order_description'         => 'Jilid hardcover skripsi dengan emboss nama, NIM, dan judul. Warna cover biru tua (ketentuan Teknik Informatika). 3 eksemplar.',
                'quantity'                  => 3,
                'order_date'                => '2025-04-28',
                'estimated_completion_date' => '2025-05-03',
                'actual_completion_date'    => null,
                'total_price'               => 195000,
                'down_payment'              => 100000,
                'payment'                   => 100000,
                'design_file'               => null,
                'notes'                     => 'File skripsi sudah diterima. Sedang proses jilid.',
                'status'                    => 'in_progress',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-04-28 14:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-04-28 13:00:00',
                'updated_at'                => '2025-04-29 09:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250505-0016',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Kalender Custom'),
                'customer_name'             => 'Klinik Sehat Bersama',
                'customer_phone'            => '081398765432',
                'customer_email'            => 'kliniksehatbersama@gmail.com',
                'order_title'               => 'Kalender Meja Klinik 2026',
                'order_description'         => 'Desain kalender meja 2026 untuk klinik. 14 lembar (cover + 12 bulan + inside back). Tiap halaman menampilkan tips kesehatan dan jadwal konsultasi dokter.',
                'quantity'                  => 1,
                'order_date'                => '2025-05-05',
                'estimated_completion_date' => '2025-05-15',
                'actual_completion_date'    => null,
                'total_price'               => 175000,
                'down_payment'              => 87500,
                'payment'                   => 87500,
                'design_file'               => null,
                'notes'                     => 'Konten tips kesehatan dikirim via dokumen Word. Foto dokter dikirim via email.',
                'status'                    => 'in_progress',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-05-05 10:30:00',
                'created_by'                => 2,
                'created_at'                => '2025-05-05 10:00:00',
                'updated_at'                => '2025-05-07 11:00:00',
            ],

            // ----------------------------------------------------------
            // STATUS: APPROVED — sudah disetujui, belum mulai dikerjakan
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250507-0017',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Brosur & Flyer'),
                'customer_name'             => 'Yayasan Pendidikan Al-Ikhlas',
                'customer_phone'            => '082173456789',
                'customer_email'            => 'ypi.alikhlas@gmail.com',
                'order_title'               => 'Brosur Penerimaan Siswa Baru 2025/2026',
                'order_description'         => 'Brosur A4 lipat 3 untuk penerimaan siswa baru SD-SMP-SMA. Informasi lengkap program unggulan, fasilitas, biaya, dan jadwal pendaftaran.',
                'quantity'                  => 1,
                'order_date'                => '2025-05-07',
                'estimated_completion_date' => '2025-05-14',
                'actual_completion_date'    => null,
                'total_price'               => 120000,
                'down_payment'              => 60000,
                'payment'                   => 60000,
                'design_file'               => null,
                'notes'                     => 'Konten sudah lengkap. Tunggu konfirmasi foto gedung baru.',
                'status'                    => 'approved',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-05-07 14:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-05-07 13:00:00',
                'updated_at'                => '2025-05-07 14:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250508-0018',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak & Jilid Skripsi / Laporan'),
                'customer_name'             => 'Ahmad Fauzi',
                'customer_phone'            => '083812345678',
                'customer_email'            => 'ahmad.fauzi@mhs.ac.id',
                'order_title'               => 'Cetak Laporan PKL Teknik Mesin',
                'order_description'         => 'Cetak laporan PKL 60 halaman, HVS 80gr, jilid softcover warna biru, 2 eksemplar.',
                'quantity'                  => 2,
                'order_date'                => '2025-05-08',
                'estimated_completion_date' => '2025-05-10',
                'actual_completion_date'    => null,
                'total_price'               => 170000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Bayar saat ambil. File sudah dikirim.',
                'status'                    => 'approved',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-05-08 09:30:00',
                'created_by'                => 2,
                'created_at'                => '2025-05-08 09:00:00',
                'updated_at'                => '2025-05-08 09:30:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250509-0019',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Kartu Nama'),
                'customer_name'             => 'Nurhaliza Fitri',
                'customer_phone'            => '089654321099',
                'customer_email'            => 'nurhaliza.freelance@gmail.com',
                'order_title'               => 'Kartu Nama Freelance Photographer',
                'order_description'         => 'Desain kartu nama minimalis untuk photographer freelance. Warna hitam putih dengan aksen emas. 2 sisi, sisi belakang portofolio QR code.',
                'quantity'                  => 1,
                'order_date'                => '2025-05-09',
                'estimated_completion_date' => '2025-05-11',
                'actual_completion_date'    => null,
                'total_price'               => 75000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Referensi sudah dikirim via Instagram DM.',
                'status'                    => 'approved',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => 1,
                'approved_at'               => '2025-05-09 11:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-05-09 10:30:00',
                'updated_at'                => '2025-05-09 11:00:00',
            ],

            // ----------------------------------------------------------
            // STATUS: PENDING — baru masuk, belum diproses admin
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250510-0020',
                'user_id'                   => 3,
                'category_id'               => $cat('Desain Spanduk & Banner'),
                'customer_name'             => 'Pelanggan',
                'customer_phone'            => '081234567891',
                'customer_email'            => 'pelanggan@example.com',
                'order_title'               => 'Banner Promo Toko Online',
                'order_description'         => 'Banner digital untuk promosi flash sale toko online di media sosial. Ukuran 1080x1080px (Instagram) dan 1200x628px (Facebook). Produk fashion wanita.',
                'quantity'                  => 2,
                'order_date'                => '2025-05-10',
                'estimated_completion_date' => '2025-05-13',
                'actual_completion_date'    => null,
                'total_price'               => 200000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Produk-produk yang akan dimasukkan ke banner dikirim via WhatsApp.',
                'status'                    => 'pending',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-05-10 08:00:00',
                'updated_at'                => '2025-05-10 08:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250510-0021',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Foto Kanvas'),
                'customer_name'             => 'Indra Pratama',
                'customer_phone'            => '081312345678',
                'customer_email'            => null,
                'order_title'               => 'Cetak Foto Keluarga di Kanvas',
                'order_description'         => 'Cetak foto keluarga di atas kanvas ukuran 40x60cm. Foto akan dikirim via WhatsApp. Dengan bingkai kayu.',
                'quantity'                  => 1,
                'order_date'                => '2025-05-10',
                'estimated_completion_date' => '2025-05-14',
                'actual_completion_date'    => null,
                'total_price'               => 150000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => '',
                'status'                    => 'pending',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-05-10 09:30:00',
                'updated_at'                => '2025-05-10 09:30:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250510-0022',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Kemasan Produk'),
                'customer_name'             => 'Dapur Kue Mama Siti',
                'customer_phone'            => '087865554321',
                'customer_email'            => 'mamasiti.kue@gmail.com',
                'order_title'               => 'Kemasan Box Kue Lebaran',
                'order_description'         => 'Desain kemasan box kue lebaran ukuran 20x20x5cm untuk 2 varian produk: nastar dan kastengel. Tampilan elegan dan premium.',
                'quantity'                  => 2,
                'order_date'                => '2025-05-10',
                'estimated_completion_date' => '2025-05-17',
                'actual_completion_date'    => null,
                'total_price'               => 500000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Referensi desain kompetitor sudah dikirim via email.',
                'status'                    => 'pending',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-05-10 11:00:00',
                'updated_at'                => '2025-05-10 11:00:00',
            ],

            // ----------------------------------------------------------
            // STATUS: REJECTED — ditolak dengan alasan jelas
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250218-0023',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Mug Custom'),
                'customer_name'             => 'Komunitas Fotografi Medan',
                'customer_phone'            => '082198765400',
                'customer_email'            => 'fotografi.medan@gmail.com',
                'order_title'               => 'Cetak Mug Custom Anggota Komunitas',
                'order_description'         => 'Cetak mug custom untuk 50 anggota komunitas fotografi. Desain sudah ada, tinggal cetak.',
                'quantity'                  => 50,
                'order_date'                => '2025-02-18',
                'estimated_completion_date' => '2025-02-25',
                'actual_completion_date'    => null,
                'total_price'               => 4250000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => '',
                'status'                    => 'rejected',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => 'Mohon maaf, layanan Cetak Mug Custom saat ini tidak tersedia karena mesin sublimasi sedang dalam perbaikan. Silakan coba lagi bulan depan atau hubungi kami untuk alternatif produk lain.',
                'approved_by'               => 1,
                'approved_at'               => '2025-02-18 15:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-02-18 14:00:00',
                'updated_at'                => '2025-02-18 15:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250402-0024',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Kaos Custom'),
                'customer_name'             => 'Panitia OSPEK Universitas',
                'customer_phone'            => '081300112233',
                'customer_email'            => 'ospek2025@univ.ac.id',
                'order_title'               => 'Kaos Panitia OSPEK 2025',
                'order_description'         => 'Cetak kaos untuk 80 panitia OSPEK. Teknik sablon, warna kaos hitam, desain 2 warna (putih dan merah). Ukuran S-XL.',
                'quantity'                  => 80,
                'order_date'                => '2025-04-02',
                'estimated_completion_date' => '2025-04-15',
                'actual_completion_date'    => null,
                'total_price'               => 9600000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => '',
                'status'                    => 'rejected',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => 'Layanan Cetak Kaos Custom saat ini tidak tersedia. Kami menyarankan untuk menghubungi vendor konveksi rekanan kami. Silakan hubungi admin untuk informasi lebih lanjut.',
                'approved_by'               => 1,
                'approved_at'               => '2025-04-02 11:00:00',
                'created_by'                => 2,
                'created_at'                => '2025-04-02 10:00:00',
                'updated_at'                => '2025-04-02 11:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250412-0025',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Logo & Brand Identity'),
                'customer_name'             => 'Nama Tidak Jelas',
                'customer_phone'            => '08000000000',
                'customer_email'            => null,
                'order_title'               => 'Desain Logo Cepat 1 Jam',
                'order_description'         => 'Minta desain logo dalam 1 jam, bayar setelah jadi saja.',
                'quantity'                  => 1,
                'order_date'                => '2025-04-12',
                'estimated_completion_date' => '2025-04-12',
                'actual_completion_date'    => null,
                'total_price'               => 350000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => '',
                'status'                    => 'rejected',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => 'Order tidak dapat diproses. Estimasi pengerjaan desain logo minimal 3-5 hari kerja. Selain itu, diperlukan DP minimum 50% sebelum pengerjaan dimulai. Silakan hubungi admin untuk informasi lebih lanjut.',
                'approved_by'               => 1,
                'approved_at'               => '2025-04-12 10:30:00',
                'created_by'                => 2,
                'created_at'                => '2025-04-12 10:00:00',
                'updated_at'                => '2025-04-12 10:30:00',
            ],

            // ----------------------------------------------------------
            // STATUS: CANCELLED — dibatalkan oleh pelanggan
            // ----------------------------------------------------------
            [
                'order_code'                => 'ORD-JAS-20250301-0026',
                'user_id'                   => null,
                'category_id'               => $cat('Desain Undangan Pernikahan'),
                'customer_name'             => 'Dian Permata',
                'customer_phone'            => '082300998877',
                'customer_email'            => 'dian.permata@gmail.com',
                'order_title'               => 'Undangan Pernikahan Tema Garden Party',
                'order_description'         => 'Desain undangan pernikahan outdoor tema garden party. Warna pastel (mint, peach, putih). Ukuran persegi 15x15cm.',
                'quantity'                  => 1,
                'order_date'                => '2025-03-01',
                'estimated_completion_date' => '2025-03-08',
                'actual_completion_date'    => null,
                'total_price'               => 200000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Dibatalkan oleh pelanggan — acara pernikahan diundur.',
                'status'                    => 'cancelled',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-03-01 10:00:00',
                'updated_at'                => '2025-03-03 09:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250408-0027',
                'user_id'                   => 3,
                'category_id'               => $cat('Desain Kemasan Produk'),
                'customer_name'             => 'Pelanggan',
                'customer_phone'            => '081234567891',
                'customer_email'            => 'pelanggan@example.com',
                'order_title'               => 'Kemasan Produk Kecantikan',
                'order_description'         => 'Desain kemasan serum wajah 30ml, box dan label botol. Tampilan premium, warna putih dan gold.',
                'quantity'                  => 2,
                'order_date'                => '2025-04-08',
                'estimated_completion_date' => '2025-04-18',
                'actual_completion_date'    => null,
                'total_price'               => 500000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Dibatalkan — pelanggan memilih menggunakan jasa desainer lain.',
                'status'                    => 'cancelled',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-04-08 13:00:00',
                'updated_at'                => '2025-04-10 11:00:00',
            ],
            [
                'order_code'                => 'ORD-JAS-20250422-0028',
                'user_id'                   => null,
                'category_id'               => $cat('Cetak Plakat & Piagam'),
                'customer_name'             => 'EO Spekta Event',
                'customer_phone'            => '081276543211',
                'customer_email'            => 'spekta.event@gmail.com',
                'order_title'               => 'Plakat Penghargaan Lomba Seni',
                'order_description'         => 'Plakat untuk 15 pemenang lomba seni tingkat kota. Bahan akrilik, desain custom per kategori lomba.',
                'quantity'                  => 15,
                'order_date'                => '2025-04-22',
                'estimated_completion_date' => '2025-04-30',
                'actual_completion_date'    => null,
                'total_price'               => 2925000,
                'down_payment'              => 0,
                'payment'                   => 0,
                'design_file'               => null,
                'notes'                     => 'Dibatalkan — event ditiadakan karena cuaca buruk.',
                'status'                    => 'cancelled',
                'status_pembayaran'         => 'belum_lunas',
                'rejection_reason'          => null,
                'approved_by'               => null,
                'approved_at'               => null,
                'created_by'                => 2,
                'created_at'                => '2025-04-22 09:00:00',
                'updated_at'                => '2025-04-24 10:00:00',
            ],
        ];

        // ============================================================
        // INSERT
        // ============================================================
        foreach ($orders as $order) {
            ServiceOrder::create($order);
        }
    }
}